import type { Organization } from "@prisma/client";
import type { TenantDb } from "@/lib/tenant-db";
import { sanitizePortableData } from "@/lib/data-portability/catalog";

export const SAFE_USER_SELECT = {
  id: true,
  email: true,
  emailVerified: true,
  name: true,
  image: true,
  theme: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const SAFE_INVITATION_SELECT = {
  id: true,
  organizationId: true,
  email: true,
  role: true,
  status: true,
  invitedById: true,
  expiresAt: true,
  acceptedAt: true,
  createdAt: true,
} as const;

export const SAFE_CREDENTIAL_SELECT = {
  id: true,
  organizationId: true,
  platformId: true,
  marketplaceAccountId: true,
  label: true,
  username: true,
  notes: true,
  lastRotatedAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

/**
 * Vollständiger, tenant-gescoppter Organisationsauszug. Die festen Abfragen
 * bleiben bewusst explizit: neue Modelle müssen sichtbar in die Coverage
 * aufgenommen werden, statt still durch generische Schema-Introspektion in
 * einen Datenschutzexport zu geraten.
 */
export async function loadOrganizationPortableData(
  db: TenantDb,
  organization: Organization
) {
  const [
    memberships,
    invitations,
    platforms,
    marketplaceAccounts,
    payoutAccounts,
    businessPartners,
    businessPartnerRoles,
    carriers,
    taxRates,
    shippingRates,
    selectOptions,
    credentialMetadata,
  ] = await Promise.all([
    db.membership.findMany({
      include: { user: { select: SAFE_USER_SELECT } },
      orderBy: { createdAt: "asc" },
    }),
    db.invitation.findMany({
      select: SAFE_INVITATION_SELECT,
      orderBy: { createdAt: "asc" },
    }),
    db.platform.findMany({ orderBy: { createdAt: "asc" } }),
    db.marketplaceAccount.findMany({ orderBy: { createdAt: "asc" } }),
    db.payoutAccount.findMany({ orderBy: { createdAt: "asc" } }),
    db.businessPartner.findMany({ orderBy: { createdAt: "asc" } }),
    db.businessPartnerRole.findMany({ orderBy: { createdAt: "asc" } }),
    db.carrier.findMany({ orderBy: { createdAt: "asc" } }),
    db.taxRate.findMany({ orderBy: { createdAt: "asc" } }),
    db.shippingRate.findMany({ orderBy: { createdAt: "asc" } }),
    db.selectOption.findMany({ orderBy: { createdAt: "asc" } }),
    db.credential.findMany({
      select: SAFE_CREDENTIAL_SELECT,
      orderBy: { createdAt: "asc" },
    }),
  ]);

  const [
    products,
    purchases,
    purchaseLines,
    purchaseReceipts,
    purchaseReceiptLines,
    inventoryPositions,
    ownedStockLots,
    consignmentLots,
    inventoryPositionListings,
    inventoryMovements,
    documentSequences,
  ] = await Promise.all([
    db.product.findMany({ orderBy: { createdAt: "asc" } }),
    db.purchase.findMany({ orderBy: { createdAt: "asc" } }),
    db.purchaseLine.findMany({ orderBy: { createdAt: "asc" } }),
    db.purchaseReceipt.findMany({ orderBy: { createdAt: "asc" } }),
    db.purchaseReceiptLine.findMany({ orderBy: { createdAt: "asc" } }),
    db.inventoryPosition.findMany({ orderBy: { createdAt: "asc" } }),
    db.ownedStockLot.findMany({ orderBy: { createdAt: "asc" } }),
    db.consignmentLot.findMany({ orderBy: { createdAt: "asc" } }),
    db.inventoryPositionListing.findMany({ orderBy: { id: "asc" } }),
    db.inventoryMovement.findMany({ orderBy: { createdAt: "asc" } }),
    db.documentSequence.findMany({ orderBy: [{ year: "asc" }, { kind: "asc" }] }),
  ]);

  const [
    sales,
    saleLines,
    saleLineAllocations,
    returns,
    returnLines,
    returnAllocations,
    supplierReturns,
    supplierReturnLines,
    debts,
    debtPurchaseLinks,
    debtSaleLinks,
    debtInventoryLinks,
  ] = await Promise.all([
    db.sale.findMany({ orderBy: { createdAt: "asc" } }),
    db.saleLine.findMany({ orderBy: { createdAt: "asc" } }),
    db.saleLineAllocation.findMany({ orderBy: { createdAt: "asc" } }),
    db.return.findMany({ orderBy: { createdAt: "asc" } }),
    db.returnLine.findMany({ orderBy: { createdAt: "asc" } }),
    db.returnAllocation.findMany({ orderBy: { createdAt: "asc" } }),
    db.supplierReturn.findMany({ orderBy: { createdAt: "asc" } }),
    db.supplierReturnLine.findMany({ orderBy: { createdAt: "asc" } }),
    db.debt.findMany({ orderBy: { createdAt: "asc" } }),
    db.debtPurchaseLink.findMany({ orderBy: { createdAt: "asc" } }),
    db.debtSaleLink.findMany({ orderBy: { createdAt: "asc" } }),
    db.debtInventoryLink.findMany({ orderBy: { createdAt: "asc" } }),
  ]);

  const [
    importBatches,
    sourceReferences,
    expenseCategories,
    expenses,
    expenseRecurrenceRules,
    feeSchedules,
    feeRules,
    feeCategories,
    productMarketplaceMappings,
    pricingCalculations,
    tasks,
    taskAssignments,
    taskChecklistItems,
    taskActivities,
    taskDomainLinks,
    featureEntitlements,
    auditLogs,
    legacyStockItems,
    legacyStockItemListings,
    legacySaleItems,
    legacyConsignments,
  ] = await Promise.all([
    db.importBatch.findMany({ orderBy: { createdAt: "asc" } }),
    db.sourceReference.findMany({ orderBy: { createdAt: "asc" } }),
    db.expenseCategory.findMany({ orderBy: { createdAt: "asc" } }),
    db.expense.findMany({ orderBy: { createdAt: "asc" } }),
    db.expenseRecurrenceRule.findMany({ orderBy: { createdAt: "asc" } }),
    db.feeSchedule.findMany({ orderBy: { createdAt: "asc" } }),
    db.feeRule.findMany({ orderBy: { createdAt: "asc" } }),
    db.feeCategory.findMany({ orderBy: { createdAt: "asc" } }),
    db.productMarketplaceMapping.findMany({ orderBy: { createdAt: "asc" } }),
    db.marketplacePricingCalculation.findMany({ orderBy: { createdAt: "asc" } }),
    db.task.findMany({ orderBy: { createdAt: "asc" } }),
    db.taskAssignment.findMany({ orderBy: { createdAt: "asc" } }),
    db.taskChecklistItem.findMany({ orderBy: { createdAt: "asc" } }),
    db.taskActivity.findMany({ orderBy: { createdAt: "asc" } }),
    db.taskDomainLink.findMany({ orderBy: { createdAt: "asc" } }),
    db.featureEntitlement.findMany({ orderBy: { createdAt: "asc" } }),
    db.auditLog.findMany({ orderBy: { createdAt: "asc" } }),
    db.stockItem.findMany({ orderBy: { createdAt: "asc" } }),
    db.stockItemListing.findMany({ orderBy: { id: "asc" } }),
    db.saleItem.findMany({ orderBy: { id: "asc" } }),
    db.consignmentInventory.findMany({ orderBy: { createdAt: "asc" } }),
  ]);

  return sanitizePortableData({
    exportedAt: new Date().toISOString(),
    format: "storagex-portable-export-v2",
    organization,
    memberships,
    invitations,
    platforms,
    marketplaceAccounts,
    payoutAccounts,
    businessPartners,
    businessPartnerRoles,
    carriers,
    taxRates,
    shippingRates,
    selectOptions,
    credentialMetadata,
    products,
    purchases,
    purchaseLines,
    purchaseReceipts,
    purchaseReceiptLines,
    inventoryPositions,
    ownedStockLots,
    consignmentLots,
    inventoryPositionListings,
    inventoryMovements,
    documentSequences,
    sales,
    saleLines,
    saleLineAllocations,
    returns,
    returnLines,
    returnAllocations,
    supplierReturns,
    supplierReturnLines,
    debts,
    debtPurchaseLinks,
    debtSaleLinks,
    debtInventoryLinks,
    importBatches,
    sourceReferences,
    expenseCategories,
    expenses,
    expenseRecurrenceRules,
    feeSchedules,
    feeRules,
    feeCategories,
    productMarketplaceMappings,
    pricingCalculations,
    tasks,
    taskAssignments,
    taskChecklistItems,
    taskActivities,
    taskDomainLinks,
    featureEntitlements,
    auditLogs,
    legacyStockItems,
    legacyStockItemListings,
    legacySaleItems,
    legacyConsignments,
  });
}
